### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by soroush-ziaeinejad** [fani-lab/SEERa#14]

**Comment by soroush-ziaeinejad** [comment]
Added CSV data
Code structure now makes more sense
Plug and play modules
All adjustable parameters are now are in params.py separated by their related layer

**Comment by hosseinfani** [comment]
@soroush-ziaeinejad 
While I was refactoring the code, I noted the following issues/concerns. You may fix them already. Please have a look and let me know what do you think.

 DataPreperation.py line 42#Hossein: what if there is no concept identified for a post => filter empty strings
 
 check other configs:
 tagme
 time only => there is no userid => the pipeline breaks at uml, gel, ...
 no user no time
 
  usersimilarity.py line 35 => is it inference or look up?
 usersimilarity.py line 35 => what if we have document = post config?
 usersimilarity.py line 39 => dense zero matrix!

**Comment by soroush-ziaeinejad** [comment]
@hosseinfani 
Thanks for your comments. 

1- We do not add a post with empty string after preprocessing, filtering, and removing stopwords.
2- Tagme, time-only, and user-only configs have been already fixed and tested.
3- Due to the massive changes in usersimilarity.py I cannot follow which lines you mean. We can discuss it in person.

Thanks.
