### ISSUE TITLE
Change the code to read from CSV files instead of DB

### ISSUE THREAD

**Issue by soroush-ziaeinejad** [fani-lab/SEERa#20]
@jalalshabo 
Please put your questions for this task as a comment under this issue.

**Comment by jalalshabo** [comment]
I am able to read from the CVS, simply need to work on the layout of the data and such to work with the exisiting code. Will discuss my questions with soroush.

**Comment by soroush-ziaeinejad** [comment]
Hi @jalalshabo 
Let me know if you have more questions about this issue. We have to finish the coding by Feb 8th and start to revise and write the paper to submit to SIGIR 22 conference. If you've had any progress on this issue, please let me know. Thanks.

**Comment by jalalshabo** [comment]
hello @soroush-ziaeinejad 

I will try to have it done by Sunday night, I will let you know if any issues come up.

**Comment by soroush-ziaeinejad** [comment]
Okay @jalalshabo Thank you.

**Comment by soroush-ziaeinejad** [comment]
Hi @jalalshabo,

Well done! Thank you so much for your clean code and your comments. It's exactly what I expected. I will merge your code, make some changes and let you know to test the whole package installation on your system in a couple of days.

**Comment by hosseinfani** [comment]
@jalalshabo and @soroush-ziaeinejad 
please ask Jalal to create a pr and then make the changes on the pr. finally merge it to the codeline. thanks.
