### ISSUE TITLE
Crawl newer tweets

### ISSUE THREAD

**Issue by soroush-ziaeinejad** [fani-lab/SEERa#21]
@jalalshabo
For this task, please write a code to extract tweets. Try to write it in a dynamic way so we can adjust arguments easily. For now, I think the most important arguments are the date range (ex. 2020-1-1 to 2020-5-1) and the number of users.

**Comment by hosseinfani** [comment]
Hi @jalalshabo and @soroush-ziaeinejad , please put this in the lower priority among the other tasks.

**Comment by hosseinfani** [comment]
@jalalshabo @soroush-ziaeinejad 
I think for our research purposes, we don't need new tweets. We have another dataset of the huge amount of tweets (~200GB).  it's already annotated with tagme too. I suggest starting working on that.

**Comment by soroush-ziaeinejad** [comment]
@hosseinfani 
Great! Is it in SQL or CSV format? Yes, we can take a look and start working on it. I am a little bit worried about the loading process!

**Comment by hosseinfani** [comment]
the rar is 200GB. in sql. it contains 10 months of the year 2010, if I'm not wrong. I'm finding the stat on it.
