### ISSUE TITLE
Find a better topic modeling approach (instead of LDA) for short text

### ISSUE THREAD

**Issue by soroush-ziaeinejad** [fani-lab/SEERa#22]
@jalalshabo
Please do some research (and maybe based on your experience) and find a better topic modeling approach for tweets. LDA works fine on long text (it's also good for tweets) but applying a specific topic modeling method is preferred. If you have any questions about the topic modeling and existing methods you can add them as comments here.

**Comment by jalalshabo** [comment]
Biterm and GSDMM seems to be the most prominant topic modeling solutions for smaller text. Will do more research and and find the pros and cons to each method.

**Comment by jalalshabo** [comment]
After some more research it seems that GSDMM will be the most likely effective approach to topic modeling for short text. Though LDA and GSDMM performace seems to be similar some research has shown that topic stability which measures the persistence of the extracted topics from different runs seems to be much more consistant with GSDMM topic modeling.

**Comment by hosseinfani** [comment]
@jalalshabo 
Thank you. Can you please share the link to the paper?

**Comment by hosseinfani** [comment]
not from top conference tho!

**Comment by jalalshabo** [comment]
Yes, sorry for the late reply. Below is the research paper.  

https://www.semanticscholar.org/paper/A-dirichlet-multinomial-mixture-model-based-for-Yin-Wang/d03ca28403da15e75bc3e90c21eab44031257e80?p2df

**Comment by hosseinfani** [comment]
@jalalshabo 
thanks. this is from A* conference!

**Comment by soroush-ziaeinejad** [comment]
Hello @jalalshabo,

It seems an interesting move to use this method in our framework (called SEERa from now on) as our based topic modeling method or as a baseline to compare our model with. For now, please try to download and run this package (https://github.com/jackyin12/MStream) on their own sample, then try to change its parameters and let us know about your experience working with that (issues, features, etc.).

Thanks

**Comment by hosseinfani** [comment]
@soroush-ziaeinejad 
log the progress for integrating the new topic modeling here. thank you.
