### ISSUE TITLE
Users similarities problem

### ISSUE THREAD

**Issue by soroush-ziaeinejad** [fani-lab/SEERa#27]
The similarities between users are not calculated properly. That's why there is a strict threshold for them to be connected to each other. Thresholds lower than 0.7 make a huge community but thresholds greater than 0.75 just keep communities that their members have exactly the same connections (Which is also not a good thing! There are multiple nodes with **exactly** the same connections in the users' graphs). 

0<Threshold<0.7:
![Graph3](https://user-images.githubusercontent.com/3676619/153768132-1aee7b0b-d756-4721-aaf6-0a449c0a0f96.jpg)

0.75<Threshold<1
![Graph3](https://user-images.githubusercontent.com/3676619/153768160-f530af92-bf93-483e-9699-a19093d23b26.jpg)

**Comment by hosseinfani** [comment]
Not sure I understood. We can discuss this in our weekly meeting.
