### ISSUE TITLE
DynamicGEM issues

### ISSUE THREAD

**Issue by soroush-ziaeinejad** [fani-lab/SEERa#38]
1. When calling AERNN, it calls __future__ library which is available from python 3.7. Thus, in yml file, python 3.7 or 3.8 should be mentioned.

**Comment by soroush-ziaeinejad** [comment]
tensorflow-gpu==1.11.0 is not available for python 3.7 and newer!!

**Comment by soroush-ziaeinejad** [comment]
@hosseinfani 

Can you please run:
from dynamicgem.embedding.dynAERNN import DynAERNN
on the system that you installed dynamicgem and let me know the result?

Thanks

**Comment by soroush-ziaeinejad** [comment]
I think commenting "#from __future__ import annotations" out in "site-packages\seaborn-0.12.0b2-py3.6.egg\seaborn\axisgrid.py" will resolve the problem

**Comment by soroush-ziaeinejad** [comment]
Now it's training

**Comment by hosseinfani** [comment]
> 1. When calling AERNN, it calls **future** library which is available from python 3.7. Thus, in yml file, python 3.7 or 3.8 should be mentioned.

but the dynamicgem works in python 3.6. AERNN is part of dynamicgem?

**Comment by hosseinfani** [comment]
> tensorflow-gpu==1.11.0 is not available for python 3.7 and newer!!

I know. we deal with gpu issues in the next round of code refactoring.

**Comment by soroush-ziaeinejad** [comment]
> > 1. When calling AERNN, it calls **future** library which is available from python 3.7. Thus, in yml file, python 3.7 or 3.8 should be mentioned.
> 
> 
> 
> but the dynamicgem works in python 3.6. How this is possible?

The AERNN calls another library (seaborn) which import __future__ library and this library is not available for python 3.6 and older. I commented out import future and it worked fine. Now the cpl part 2 (the bottleneck) is running on the workstation.

**Comment by hosseinfani** [comment]
> from dynamicgem.embedding.dynAERNN import DynAERNN

I found the reason. DynamicGem wants seaborn>=0.9.0. The current version of seaborn (0.12) needs python 3.7. 
I believe if you put seaborn==0.9.0 or 0.11.0, in *our* environment.yml and requirement.txt, dynamicgem sees that and won't look for latest version. I checked it and it worked.

**Comment by soroush-ziaeinejad** [comment]
### **Graph embedding results**


Setting 1:
----------------
**Epochs:** 150
**Dimension:** 128
**embedding.max():** 0
**embedding.min():** 0

Setting 2:
----------------
**Epochs:** 10
**Dimension:** 64
**embedding.max():**  0.0017
**embedding.min():** -0.0019

Setting 3:
----------------
**Epochs:** 10
**Dimension:** 128
**embedding.max():**  0.0054
**embedding.min():** -0.0061
