### ISSUE TITLE
Same results of different models in Evaluation

### ISSUE THREAD

**Issue by farinamhz** [fani-lab/SEERa#51]
Two models in topic modeling layer (LDA.mallet and btm) give similar results for success in evaluation.

**Comment by farinamhz** [comment]
@soroush-ziaeinejad
Could you please check the new code and test it to make sure that this bug is resolved to close the issue?

**Comment by soroush-ziaeinejad** [comment]
Hi @farinamhz ,

I have a problem with installing bitermplus. Could you please send me the version of bitermplus that you have installed?

**Comment by hosseinfani** [comment]
@soroush-ziaeinejad 
Is this open or solved? If solved, close it please.

**Comment by soroush-ziaeinejad** [comment]
@hosseinfani It is solved. I'll close it.
