### ISSUE TITLE
Log file overwriting issue 

### ISSUE THREAD

**Issue by soroush-ziaeinejad** [fani-lab/SEERa#58]
Hi @Sharjeeliv,

I created this issue page for your second task on SEERa. As you know, we log the outputs and messages for each run of SEERa. The problem is when we run it on the same folder, it overwrites the log file and we miss the previous information in this file. 

For example, suppose SEERa has been run and lots of information is written for the topic modeling layer (2nd layer) and then we got an error in user modeling layer (3rd layer). When we fix the problem and rerun the SEERa it overwrites "topic model is loaded" with the whole previous information that is generated during the topic modeling layer before. 

Your task is to rename the log file and add date and time of that run in a proper format (like Log.YYMMDD.HHMM) in order to avoid overwriting. In this way, we will have a separate log file for each run distinguished by date and time.

Please feel free to ask your questions regarding this task in this issue page. 

@hosseinfani, please feel free to add your comments on this issue.

Thanks.

**Comment by soroush-ziaeinejad** [comment]
Hi @Sharjeeliv ,

I hope everything is fine with you and your course work. I know you may be busy with your exams but do you have any updates on this task? Actually, it is a mini task for SEERa. Please update me when it's done so I can give you another task. Your next task is applying KMeans to the output of our graph embedding layer in order to reach user clusters. I will give you more details when you're done with this task.

**Comment by Sharjeeliv** [comment]
Hi @soroush-ziaeinejad,

Sorry for the delay, I've looked at the task and it seems pretty straightforward. I'll have a PR ready for tomorrow.

**Comment by soroush-ziaeinejad** [comment]
Thanks @Sharjeeliv

**Comment by Sharjeeliv** [comment]
Hi @soroush-ziaeinejad,

I think everything is removed instead of my changed just being added in, based on how I was told to implement changes (https://github.com/fani-lab/SEERa/issues/46#issuecomment-1286765186)

**Comment by soroush-ziaeinejad** [comment]
Thanks @Sharjeeliv for letting me know. I fixed it.
